---
title: Dansende eenhoorns en regenbogen
hero_image: images/banner.png
description: Maak een eenhoorn die synchroon danst met een LED regenboog
theme: violet #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: humour, games
technologies: electronic-components, scratch
site_areas: projects
hardware: elektronische componenten
software: scratch
version: 4
last_tested: 2018-02-01
steps:
  - title: Inleiding
  - title: "De sfeer van je regenboog"
  - title: "Jouw eerste kleur van je regenboog"
  - title: Test je circuit in Scratch
  - title: Bestuur je regenboogcircuit
  - title: Bouw je regenboog
  - title: Verlicht je regenboog
  - title: Maak een dansende eenhoorn
  - title: Een knop toevoegen
  - title: "Uitdaging: plezier met je dansende eenhoorn regenboog"
    challenge: true
  - title: Wat kun je verder nog doen?
