title: dancing-unicorn-rainbow
hero_image: images/banner.png
description: dancing-unicorn-rainbow description
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "fantasy, jokes, nature/outside/weather, physical computing, games"
technologies: "electronics, physical computing, html/css, scratch"
site_areas:
steps:
  - title: Introduction
  - title: What You Will Need
  - title: GPIO Pins
  - title: Light an LED
  - title: Test Circuit in Scratch
  - title: Build Your Rainbow
  - title: Rainbow Dancing Unicorn
  - title: Add a Button
  - title: Buzzer Game Challenge
