title: Dancing unicorns and rainbows
hero_image: images/banner.png
description: Create a unicorn that dances in time with an LED rainbow
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "fantasy, jokes, nature/outside/weather, physical computing, games"
technologies: "electronics, physical computing, html/css, scratch"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: "Your rainbow's atmosphere"
  - title: "Your rainbow's first colour"
  - title: Test your circuit in Scratch
  - title: Control your rainbow circuit
  - title: Build your rainbow
  - title: Light your rainbow
  - title: Rainbow dancing unicorn
  - title: Add a button
  - title: Buzzer challenge
