---
title: नाचते-गाते काल्पनिक जानवर और इंद्रधनुष
hero_image: images/banner.png
description: एक काल्पनिक जानवर बनाए जो LED इंद्रधनुष के साथ नाचें
theme: violet #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: humour, games
technologies: electronic-components, scratch
site_areas: प्रोजेक्ट
hardware: electronic-components
software: scratch
version: 4
last_tested: 2018-02-01
steps:
  - 
    title: परिचय
  - 
    title: "आपके इंद्रधनुष का वातावरण"
  - 
    title: "आपके इंद्रधनुष का पहला रंग"
  - 
    title: Scratch में अपने सर्किट का परीक्षण करें
  - 
    title: अपने इंद्रधनुष सर्किट को नियंत्रित करें
  - 
    title: अपना इंद्रधनुष बनाएं
  - 
    title: अपने इंद्रधनुष को प्रकाशित करें
  - 
    title: नाचने वाला काल्पनिक जानवर बनाना
  - 
    title: एक बटन जोड़ें
  - 
    title: "चुनौती: अपने काल्पनिक जानवर और इंद्रधनुष के साथ मज़ा।"
    challenge: true
  - 
    title: आगे क्या?
