---
title: Unicornios y arcoiris que bailan
hero_image: images/banner.png
description: Crea un unicornio que baile al compás de un arcoiris LED
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: humour, games
technologies: electronic-components, scratch
site_areas: projects
hardware: electronic-components
software: scratch
version: 4
last_tested: 2018-02-01
steps:
- title: Introducción
- title: La atmósfera de tu arcoiris
- title: El primer color de tu arcoiris
  completion:
  - engaged
- title: Prueba tu circuito en Scratch
- title: Controla tu circuito arcoiris
- title: Construye tu arcoiris
- title: Enciende tu arcoiris
- title: Haz un unicornio que baila
- title: Añade un botón
  completion:
  - internal
- title: 'Desafío: Diversión con tu unicornio arcoiris que baila'
  challenge: true
- title: "¿Qué sigue?"
