---
title: Unicornios y arcoíris que bailan
hero_image: images/banner.png
description: Crea un unicornio que baile al compás de un arcoíris LED
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: humour, games
technologies: electronic-components, scratch
site_areas: projects
hardware: electronic-components
software: scratch
version: 4
last_tested: 2018-02-01
steps:
  - 
    title: Introducción
  - 
    title: La atmósfera de tu arcoíris
  - 
    title: El primer color de tu arcoíris
    completion:
      - engaged
  - 
    title: Prueba tu circuito en Scratch
  - 
    title: Controla tu circuito arcoíris
  - 
    title: Construye tu arcoíris
  - 
    title: Ilumina tu arcoíris
  - 
    title: Haz un unicornio que baila
  - 
    title: Añade un botón
    completion:
      - internal
  - 
    title: 'Desafío: Diversión con tu unicornio arcoíris que baila.'
    challenge: true
  - 
    title: '¿Qué sigue?'
