---
title: وحيدي القرن وأقواس قزح راقصة
hero_image: images/banner.png
description: إنشاء وحيد قرن يرقص بنفس الوقت مع ضوء (LED) قوس قزح
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: الفكاهة والألعاب
technologies: المكونات الالكترونية، برنامج scratch
site_areas: codeclub, python
hardware: المكونات الإلكترونية
software: scratch
version: 4
last_tested: 2018-02-01
steps:
  - 
    title: المقدمة
  - 
    title: الجو الخاص بقوس قزحك
  - 
    title: اللون الاول لقوس قزح الخاص بك
    completion:
      - engaged
  - 
    title: اختبار الدائرة الخاصة بك في برنامج Scratch
  - 
    title: التحكم في دائرة قوس قزح
  - 
    title: بناء قوس قزحك
  - 
    title: أضيء قوس قزحك
  - 
    title: اصنع وحيد قرن راقص
  - 
    title: إضافة زر
    completion:
      - internal
  - 
    title: 'التحدي: المرح مع قوس قزح وحيد القرن الراقص.'
    challenge: true
  - 
    title: ما التالي؟
