---
title: Tańczące jednorożce i tęcze
hero_image: images/banner.png
description: Stwórz jednorożca, który tańczy w tym samym czasie co tęcza LED
theme: violet #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: humour, games
technologies: electronic-components, scratch
site_areas: projekty
hardware: electronic-components
software: scratch
version: 4
last_tested: 2018-02-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: "Atmosfera twojej tęczy"
  - 
    title: "Pierwszy kolor twojej tęczy"
  - 
    title: Przetestuj swój obwód w Scratchu
  - 
    title: Kontroluj obwód twojej tęczy
  - 
    title: Zbuduj swoją tęczę
  - 
    title: Zapal swoją tęczę
  - 
    title: Zrób tańczącego jednorożca
  - 
    title: Dodaj przycisk
  - 
    title: "Wyzwanie: baw się tańczącym jednorożcem i tęczą."
    challenge: true
  - 
    title: Co dalej?
