---
title: Unicorni danzanti e arcobaleni
hero_image: images/banner.png
description: Crea un unicorno che danza a tempo con un arcobaleno LED
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: humour, games
technologies: electronic-components, scratch
site_areas: projects
hardware: electronic-components
software: scratch
version: 4
last_tested: 2018-02-01
steps:
  - 
    title: Introduzione
  - 
    title: L'atmosfera del tuo arcobaleno
  - 
    title: Il primo colore del tuo arcobaleno
    completion:
      - engaged
  - 
    title: Prova il tuo circuito in Scratch
  - 
    title: Controlla il circuito dell'arcobaleno
  - 
    title: Costruisci il tuo arcobaleno
  - 
    title: Accendi il tuo arcobaleno
  - 
    title: Crea un unicorno danzante
  - 
    title: Aggiungi un pulsante
    completion:
      - internal
  - 
    title: 'Sfida: divertiti con il tuo arcobaleno degli unicorni danzanti.'
    challenge: true
  - 
    title: E poi?
